server:
  port: 8080

logging:
  config: classpath:logback/logback-dev.xml

  pattern:
    console: '%d %-5level %logger{32} - %msg%n'

  level:
    org.springframwork.web: INFO
    com.fykj: DEBUG

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fykjtest?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123
    initialSize: 5
    minIdle: 5
    maxIdle: 30
    maxActive: 30
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    plugins: [com.org.platform.filter.SchemaInterceptor]

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1
        min-idle: 0
    timeout: 1000

  application:
    name: wxDev

mybatis:
  mapperLocations: classpath:mapper/mapper-*.xml
  typeAliasesPackage: com.fykj.wxDev.pojo


wx:
  token: testUrl
  appId: wxf27c2fa67e51adaa
  appSecret: 5f7a214cae7a0967bf83f0859f4c164f
  accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s
  menuUrl: https://api.weixin.qq.com/cgi-bin/menu/create?access_token=%s
  autoTokenSwitch: 1

jobSwitch:
  quartzJobTemplate: 0

cookie:
  domain: 127.0.0.1

rocketmq:
  groupName: ${spring.application.name}
  namesrvAddr: 127.0.0.1:9876
  producer:
    default: false
  consumer:


