spring:
  profiles:
    active: dev

datasource:
  maxActive:  20
  initialSize: 5
  maxWait: 60000
  minIdle: 5
  maxIdle: 20
  validationQuery: SELECT 1
  minEvictableIdleTimeMills: 1200000
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
  testOnBorrow: true
  testOnReturn: false
  poolPreparedStatements: true
  maxOpenPreparedStatements: 20
  maxPoolPreparedStatementPerConnectionSize: 20
  filters:
    commons-log.connection-logger-name: stat,wall,log4j
